# Generated by Django 6.0.6 on 2026-06-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('role', models.IntegerField(choices=[(1, 'Manager'), (2, 'Employee')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='Date Of Expense')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Denied')], default=1)),
                ('comment', models.CharField(max_length=255)),
                ('approved_date', models.DateTimeField(verbose_name='Date Review Decision Made')),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.expense')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.user')),
            ],
        ),
    ]
