# Generated by Django 6.0.6 on 2026-06-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='Date Of Expense')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Of Review')),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.expense')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.user')),
            ],
        ),
    ]
