# Generated by Django 6.0.6 on 2026-06-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MEALS', 'Meals'), ('TRAVEL', 'Travel'), ('LODGING', 'Lodging'), ('OFFICE', 'Office'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
