# Generated by Django 6.0.6 on 2026-06-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='comment',
            field=models.CharField(max_length=30),
        ),
    ]
