# Generated by Django 6.0.6 on 2026-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0003_alter_approval_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
