# Generated by Django 6.0.6 on 2026-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0004_alter_approval_comment_alter_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved_date',
            field=models.DateTimeField(verbose_name='Date Of Review'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='comment',
            field=models.CharField(max_length=25),
        ),
    ]
