# Generated by Django 6.0.6 on 2026-06-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0005_alter_approval_approved_date_alter_approval_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Of Review'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='comment',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.user'),
        ),
    ]
